### ISSUE TITLE
Examples/factorial.val fail to compile (incorrect generated C++)

### ISSUE THREAD

**Issue by rsms** [val-lang/val#216]
```shell
$ .build/x86_64-apple-macosx/release/valc Examples/factorial.val
/var/folders/bp/shkzc7396mz4_d7mdxm4yyhr0000gn/T/TemporaryItems/(A Document Being Saved By valc 2)/main.cpp:9:20: error: expected ';' after expression
(void) factorial(6)}
                   ^
                   ;
1 error generated.
$
```

Val 83ded0876a6d51240a8d5969f46d30d3d00d7241

**Comment by kyouko-taiga** [comment]
@lucteo can you have a look?

**Comment by spinicist** [comment]
I see the same error (on Mac as well). In addition I still can't compile a simple Hello World, I get:

`
Hello.val:2:3: error: undefined name 'print' in this scope
  print("Hello World!")
  ~~~~~
`

**Comment by kyouko-taiga** [comment]
Thank you for confirming the issue.

The hello world is a separate problem. The standard library has not been completed yet, which is why `print` is not in scope in your program. Unfortunately, our implementation currently lags a little behind our documentation (e.g., `CLI.md`). Apologies for that.

**Comment by spinicist** [comment]
Thanks for the explanation - I'm excited to start experimenting with Val.

**Comment by C-BJ** [comment]
I think it is fixed? @kyouko-taiga

**Comment by spinicist** [comment]
Yes, on my machine with the `main` branch `factorial.val` now compiles :-)

(Hello World still doesn't though)

**Comment by kyouko-taiga** [comment]
Factorial is fixed.

Hello world won't work because I have yet to implement `String` is the standard library ;)
